default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:738444348690:android:2fec86642f18b3e7e2f7cb",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    groups: "testers",
    release_notes: "- Added fonts Cairo and SourceSans3\n- Add product to favorites when tap on item 2 times",
  )
  end
end
