name: Android Fastlane with Firebase App Distribution Workflow

on: 
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
          working-directory: android
        
      - name: Create .env file
        run: |
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHED_KEY }}" > .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" > .env

      - name: Flutter build
        run: |
          flutter pub get
        working-directory: android


      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec fastlane android firebase_distribution
        working-directory: android
        

        